"""create conversations, participants and messages tables

Revision ID: 81ee78e878a1
Revises: b6e1437c4409
Create Date: 2026-02-20 23:07:05.749432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81ee78e878a1'
down_revision: Union[str, Sequence[str], None] = 'b6e1437c4409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conversations',
        sa.Column(
            'id',
            sa.UUID(),
            server_default=sa.text('uuid_generate_v4()'),
            nullable=False,
        ),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('avatar_url', sa.String(length=500), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['created_by'], ['users.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_conversations_created_by',
        'conversations',
        ['created_by'],
        unique=False,
    )
    op.create_table(
        'messages',
        sa.Column(
            'id',
            sa.UUID(),
            server_default=sa.text('uuid_generate_v4()'),
            nullable=False,
        ),
        sa.Column('conversation_id', sa.UUID(), nullable=False),
        sa.Column('sender_id', sa.UUID(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('message_type', sa.String(length=50), nullable=False),
        sa.Column(
            'metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('reply_to_message_id', sa.UUID(), nullable=True),
        sa.Column('is_edited', sa.Boolean(), nullable=False),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['reply_to_message_id'], ['messages.id'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_messages_conversation',
        'messages',
        ['conversation_id', 'created_at'],
        unique=False,
    )
    op.create_index(
        'idx_messages_created', 'messages', ['created_at'], unique=False
    )
    op.create_index(
        'idx_messages_sender', 'messages', ['sender_id'], unique=False
    )
    op.create_table(
        'conversation_participants',
        sa.Column(
            'id',
            sa.UUID(),
            server_default=sa.text('uuid_generate_v4()'),
            nullable=False,
        ),
        sa.Column('conversation_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column(
            'joined_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('last_read_message_id', sa.UUID(), nullable=True),
        sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'notification_settings',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['last_read_message_id'], ['messages.id'], ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('conversation_id', 'user_id'),
    )
    op.create_index(
        'idx_participants_conversation',
        'conversation_participants',
        ['conversation_id'],
        unique=False,
    )
    op.create_index(
        'idx_participants_user',
        'conversation_participants',
        ['user_id'],
        unique=False,
    )

    for table in ("conversations", "messages"):
        op.execute(
            f"""
            CREATE TRIGGER update_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_messages_updated_at ON messages")
    op.execute(
        "DROP TRIGGER IF EXISTS update_conversations_updated_at ON conversations"
    )
    op.drop_index(
        'idx_participants_user', table_name='conversation_participants'
    )
    op.drop_index(
        'idx_participants_conversation', table_name='conversation_participants'
    )
    op.drop_table('conversation_participants')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_created', table_name='messages')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_conversations_created_by', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
